[animation.chest_closed]
    texture = "furniture.png"
    tilesize = 48
    frameDuration = 1
    loop = [14]
[animation.chest_opening]
    texture = "furniture.png"
    tilesize = 48
    frameDuration = 0.1
    sequence = [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]

[prototype.chest]
    inherits = "furniture"
    animation = "chest_closed"
    boundingBox = [22, 6]
	drawOffset = [24, 12]
    health = 50

