[animation.door_horizontal]
    texture = "door.png"
    tilesize = 96
    frameDuration = 1
    loop = [1]
[animation.door_vertical]
    texture = "door.png"
    tilesize = 96
    frameDuration = 1
    loop = [0]

[prototype.door_horizontal]
    inherits = "furniture"
    animation = "door_horizontal"
    boundingBox = [7, 48]
    drawOffset = [47, 32]
    health = 10
[prototype.door_horizontal_opening]
    inherits = "door_horizontal"
    animation = "door_horizontal"
    timeToLive = 1
    zSpeed = 40
    fadeOut = 1
    canBeHurt = false
[prototype.door_vertical]
    inherits = "furniture"
    animation = "door_vertical"
    boundingBox = [48, 48]
    drawOffset = [48, 48]
    health = 10
[prototype.door_vertical_opening]
    inherits = "door_vertical"
    animation = "door_vertical"
    timeToLive = 1
    zSpeed = 40
    fadeOut = 1
    canBeHurt = false
