#
# Bookcase
#
[animation.prop_bookshelf]
    texture = "furniture.png"
    tilesize = 48
    frameDuration = 1
    loop = [0]

[prototype.prop_bookshelf]
    animation = "prop_bookshelf"
    boundingBox = [48, 38]
    drawOffset = [24, 24]
    health = 500
    solid = true
    castsShadow = true

#
# Tables
#
[animation.prop_table_1]
    texture = "furniture.png"
    tilesize = 48
    frameDuration = 1
    loop = [1]
[animation.prop_table_2]
    texture = "furniture.png"
    tilesize = 48
    frameDuration = 1
    loop = [2]

[prototype.prop_table_1]
    animation = "prop_table_1"
    boundingBox = [42, 20]
    drawOffset = [24, 24]
    health = 500
    solid = true
    castsShadow = true
[prototype.prop_table_2]
    animation = "prop_table_2"
    boundingBox = [42, 20]
    drawOffset = [24, 24]
    health = 500
    solid = true
    castsShadow = true

#
# Cage
#
[animation.prop_cage]
    texture = "furniture.png"
    tilesize = 48
    frameDuration = 1
    loop = [3]

[prototype.prop_cage]
    animation = "prop_cage"
    boundingBox = [20, 36]
    drawOffset = [24, 24]
    health = 1000
    solid = true
    castsShadow = true

#
# Paintings
#
[animation.prop_painting_1]
    texture = "furniture.png"
    tilesize = 48
    frameDuration = 1
    loop = [28]
[animation.prop_painting_2]
    texture = "furniture.png"
    tilesize = 48
    frameDuration = 1
    loop = [29]
[animation.prop_painting_3]
    texture = "furniture.png"
    tilesize = 48
    frameDuration = 1
    loop = [30]

[prototype.prop_painting_1]
    animation = "prop_painting_1"
    boundingBox = [24, 28]
    drawOffset = [24, 24]
    health = 100
    solid = true
[prototype.prop_painting_2]
    animation = "prop_painting_2"
    boundingBox = [24, 28]
    drawOffset = [24, 24]
    health = 100
    solid = true
[prototype.prop_painting_3]
    animation = "prop_painting_3"
    boundingBox = [24, 28]
    drawOffset = [24, 24]
    health = 100
    solid = true
