#
# Particles
#

# Wood chips
[animation.wood_particle_1]
    texture = "particles.png"
    tilesize = 8
    frameDuration = 1.0
    sequence = [0]
[animation.wood_particle_2]
    texture = "particles.png"
    tilesize = 8
    frameDuration = 1.0
    sequence = [1]
[animation.wood_particle_3]
    texture = "particles.png"
    tilesize = 8
    frameDuration = 1.0
    sequence = [2]
[animation.wood_particle_4]
    texture = "particles.png"
    tilesize = 8
    frameDuration = 1.0
    sequence = [3]
[animation.wood_particle_5]
    texture = "particles.png"
    tilesize = 8
    frameDuration = 1.0
    sequence = [4]
[animation.wood_particle_6]
    texture = "particles.png"
    tilesize = 8
    frameDuration = 1.0
    sequence = [5]
[animation.wood_particle_7]
    texture = "particles.png"
    tilesize = 8
    frameDuration = 1.0
    sequence = [6]
[animation.wood_particle_8]
    texture = "particles.png"
    tilesize = 8
    frameDuration = 1.0
    sequence = [7]

# Stone chips
[animation.stone_particle_1]
    texture = "particles.png"
    tilesize = 8
    frameDuration = 1.0
    sequence = [8]
[animation.stone_particle_2]
    texture = "particles.png"
    tilesize = 8
    frameDuration = 1.0
    sequence = [9]
[animation.stone_particle_3]
    texture = "particles.png"
    tilesize = 8
    frameDuration = 1.0
    sequence = [10]
[animation.stone_particle_4]
    texture = "particles.png"
    tilesize = 8
    frameDuration = 1.0
    sequence = [11]
[animation.stone_particle_5]
    texture = "particles.png"
    tilesize = 8
    frameDuration = 1.0
    sequence = [12]
[animation.stone_particle_6]
    texture = "particles.png"
    tilesize = 8
    frameDuration = 1.0
    sequence = [13]
[animation.stone_particle_7]
    texture = "particles.png"
    tilesize = 8
    frameDuration = 1.0
    sequence = [14]
[animation.stone_particle_8]
    texture = "particles.png"
    tilesize = 8
    frameDuration = 1.0
    sequence = [15]
[animation.leave_particle]
    texture = "particles.png"
    tilesize = 8
    frameDuration = 0.05
    loop = [48, 48, 48, 49, 50, 51, 52, 53, 54, 55, 56, 56, 56, 55, 54, 53, 52, 51, 50, 49]

# Droplets
[animation.droplet_start]
    texture = "particles.png"
    tilesize = 8
    frameDuration = 0.05
    sequence = [16, 17, 18, 19]
[animation.droplet_fall]
    texture = "particles.png"
    tilesize = 8
    frameDuration = 0.05
    sequence = [20]
[animation.droplet_end]
    texture = "particles.png"
    tilesize = 8
    frameDuration = 0.05
    sequence = [21, 22, 23]

# Fireball
[animation.fireball]
    texture = "particles.png"
    tilesize = 8
    frameDuration = 0.05
    loop = [24, 25, 26, 27, 28, 29, 30, 31]

# Flame
[animation.flame]
    texture = "particles.png"
    tilesize = 8
    frameDuration = 0.05
    loop = [32, 33, 34, 35, 36, 37, 38, 39]

# Candle
[animation.candle]
    texture = "particles.png"
    tilesize = 8
    frameDuration = 0.05
    loop = [40, 41, 42, 43, 44, 45, 46, 47]
