#
# Bushes
#
[prototype.bush]
    inherits = "furniture"
    boundingBox = [22, 22]
    drawOffset = [24, 23]
    health = 200
[prototype.bush_small]
    inherits = "furniture"
    boundingBox = [12, 12]
    drawOffset = [24, 24]
    health = 100

# Green
[prototype.prop_bush_green]
    inherits = "bush"
    animation = "prop_bush_green"
[animation.prop_bush_green]
    texture = "furniture.png"
    tilesize = 48
    frameDuration = 1
    loop = [4]

# Green (small)
[prototype.prop_bush_green_small]
    inherits = "bush_small"
    animation = "prop_bush_green_small"
[animation.prop_bush_green_small]
    texture = "furniture.png"
    tilesize = 48
    frameDuration = 1
    loop = [5]

# Gold
[prototype.prop_bush_gold]
    inherits = "bush"
    animation = "prop_bush_gold"
[animation.prop_bush_gold]
    texture = "furniture.png"
    tilesize = 48
    frameDuration = 1
    loop = [6]

# Gold (small)
[prototype.prop_bush_gold_small]
    inherits = "bush_small"
    animation = "prop_bush_gold_small"
[animation.prop_bush_gold_small]
    texture = "furniture.png"
    tilesize = 48
    frameDuration = 1
    loop = [7]

# Red
[prototype.prop_bush_red]
    inherits = "bush"
    animation = "prop_bush_red"
[animation.prop_bush_red]
    texture = "furniture.png"
    tilesize = 48
    frameDuration = 1
    loop = [8]

# Red (small)
[prototype.prop_bush_red_small]
    inherits = "bush_small"
    animation = "prop_bush_red_small"
[animation.prop_bush_red_small]
    texture = "furniture.png"
    tilesize = 48
    frameDuration = 1
    loop = [9]

# Cyan
[prototype.prop_bush_cyan]
    inherits = "bush"
    animation = "prop_bush_cyan"
[animation.prop_bush_cyan]
    texture = "furniture.png"
    tilesize = 48
    frameDuration = 1
    loop = [10]

# Cyan (small)
[prototype.prop_bush_cyan_small]
    inherits = "bush_small"
    animation = "prop_bush_cyan_small"
[animation.prop_bush_cyan_small]
    texture = "furniture.png"
    tilesize = 48
    frameDuration = 1
    loop = [11]

# Purple
[prototype.prop_bush_purple]
    inherits = "bush"
    animation = "prop_bush_purple"
[animation.prop_bush_purple]
    texture = "furniture.png"
    tilesize = 48
    frameDuration = 1
    loop = [12]

# Purple (small)
[prototype.prop_bush_purple_small]
    inherits = "bush_small"
    animation = "prop_bush_purple_small"
[animation.prop_bush_purple_small]
    texture = "furniture.png"
    tilesize = 48
    frameDuration = 1
    loop = [13]

#
# Grass
#

# Grass 1
[animation.prop_grass_1]
    texture = "grass.png"
    tilesize = 24
    frameDuration = 0.5
    loop = [0, 1, 2, 1]
[prototype.prop_grass_1]
    animation = "prop_grass_1"
    boundingBox = [16, 18]
    drawOffset = [12, 10]
    health = 1
    solid = false
    canBeHit = true

# Grass 2
[animation.prop_grass_2]
    texture = "grass.png"
    tilesize = 24
    frameDuration = 0.8
    loop = [3, 4]
[prototype.prop_grass_2]
    animation = "prop_grass_2"
    boundingBox = [5, 4]
    drawOffset = [12, 3]
    health = 1
    solid = false
    canBeHit = true

# Grass 3
[animation.prop_grass_3]
    texture = "grass.png"
    tilesize = 24
    frameDuration = 0.8
    loop = [5, 6, 7, 6]
[prototype.prop_grass_3]
    animation = "prop_grass_3"
    boundingBox = [6, 6]
    drawOffset = [12, 4]
    health = 1
    solid = false
    canBeHit = true

# Flower 1
[animation.prop_flower_1]
    texture = "grass.png"
    tilesize = 24
    frameDuration = 0.5
    loop = [8, 8, 9, 10, 10, 9]
[prototype.prop_flower_1]
    animation = "prop_flower_1"
    boundingBox = [10, 16]
    drawOffset = [12, 15]
    health = 1
    solid = false
    canBeHit = true
