[animation.torch_idle]
    texture = "torch.png"
    tilesize = 32
    frameDuration = 0.05
    loop = [0, 1, 2, 3, 4, 5, 6, 7]

[prototype.torch]
    animation = "torch_idle"
    boundingBox = [10, 10]
	drawOffset = [16, 16]
    light = ["80", "ffb232", "NORMAL", "torchlight"]
    solid = false
