[environment.dungeon]
    tileset = "dungeon"
    light = { h = 0.6, s = 0.8, v = 0.3 }
    rooms = ["empty_room", "dinning_room", "library", "columns_room", "torture_room", "cross_room", "horizontal_hallway", "vertical_hallway", "chest_room"]
    monsters = ["creature_ghost", "creature_slime", "creature_slime_acid", "creature_slime_fire"]

# Tileset
[tileset.dungeon]
	texture = "dungeon_tileset.png"
	tilesize = 48
	out = [32]
	floor = [22, 23, 30, 31]
	convexDL = [16]
	convexDR = [17]
	convexUL = [24]
	convexUR = [25]
	concaveDL = [8]
	concaveDR = [9]
	concaveUL = [0]
	concaveUR = [1]
	concaveDown = [10, 11, 12, 13]
	concaveUp = [2, 3, 4, 5]
	concaveLeft = [18, 19, 20, 21]
	concaveRight = [26, 27, 28, 29]
	wallDecor1 = [34]
	wallDecor2 = [35]
	wallDecor3 = [36]
	wallDecor4 = [37]

# Rooms
[room.empty_room]
	tiles = [
		["VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID"]
	]
	connections = [
		{x = 0, y = 3, type = "LEFT"},
		{x = 6, y = 3, type = "RIGHT"},
		{x = 3, y = 6, type = "UP"},
		{x = 3, y = 0, type = "DOWN"}
	]
	spawns = [
		{x = 2, y = 2},
		{x = 2, y = 3.5},
		{x = 2, y = 5},
		{x = 3.5, y = 2},
		{x = 3.5, y = 5},
		{x = 5, y = 2},
		{x = 5, y = 3.5},
		{x = 5, y = 5}
	]
	placeholders = [
		# Torches
		{x = 2.5, y = 6, type = "torch"},
		{x = 4.5, y = 6, type = "torch"},
		{x = 1, y = 4, type = "torch"},
		{x = 1, y = 2, type = "torch"},
		{x = 6, y = 4, type = "torch"},
		{x = 6, y = 2, type = "torch"},
		{x = 3.5, y = 3, type = "health_powerup", chance = 0.2},
	]

[room.dinning_room]
	tiles = [
		["VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID"]
	]
	connections = [
		{x = 0, y = 3, type = "LEFT"},
		{x = 6, y = 3, type = "RIGHT"},
		{x = 3, y = 6, type = "UP"},
		{x = 3, y = 0, type = "DOWN"}
	]
	spawns = [
		{x = 2, y = 3.5},
		{x = 2, y = 5},
		{x = 3.5, y = 2},
		{x = 5, y = 2},
	]
	placeholders = [
		# Torches
		{x = 2.5, y = 6, type = "torch"},
		{x = 4.5, y = 6, type = "torch"},
		{x = 1, y = 4, type = "torch"},
		{x = 1, y = 2, type = "torch"},
		{x = 6, y = 4, type = "torch"},
		{x = 6, y = 2, type = "torch"},
		# Furniture
		{x = 5, y = 5, type = "prop_table_1"},
		{x = 4, y = 5, type = "prop_table_1"},
		{x = 5, y = 3.5, type = "prop_table_2"},
		{x = 4, y = 3.5, type = "prop_table_1"},
		{x = 2, y = 2, type = "health_powerup", chance = 0.2},
	]

[room.library]
	tiles = [
		["VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID"]
	]
	connections = [
		{x = 0, y = 3, type = "LEFT"},
		{x = 10, y = 3, type = "RIGHT"},
		{x = 5, y = 6, type = "UP"},
		{x = 5, y = 0, type = "DOWN"}
	]
	spawns = [
		{x = 3, y = 1.5},
		{x = 3, y = 3.5},
		{x = 3, y = 5.5},
		{x = 5.5, y = 2},
		{x = 5.5, y = 4},
		{x = 8, y = 1.5},
		{x = 8, y = 3.5},
		{x = 8, y = 5.5}
	]
	placeholders = [
		# Torches
		{x = 4.5, y = 6, type = "torch"},
		{x = 6.5, y = 6, type = "torch"},
		{x = 1, y = 4, type = "torch"},
		{x = 1, y = 2, type = "torch"},
		{x = 10, y = 4, type = "torch"},
		{x = 10, y = 2, type = "torch"},

		{x = 3, y = 4.24, type = "torch"},
		{x = 8, y = 4.24, type = "torch"},
		{x = 3, y = 2.24, type = "torch"},
		{x = 8, y = 2.24, type = "torch"},
		# Furniture
		{x = 1.5, y = 5.75, type = "prop_bookshelf"},
		{x = 2.5, y = 5.75, type = "prop_bookshelf"},
		{x = 3.5, y = 5.75, type = "prop_bookshelf"},
		{x = 7.5, y = 5.75, type = "prop_bookshelf"},
		{x = 8.5, y = 5.75, type = "prop_bookshelf"},
		{x = 9.5, y = 5.75, type = "prop_bookshelf"},

		{x = 2.5, y = 4.25, type = "prop_bookshelf"},
		{x = 3.5, y = 4.25, type = "prop_bookshelf"},
		{x = 7.5, y = 4.25, type = "prop_bookshelf"},
		{x = 8.5, y = 4.25, type = "prop_bookshelf"},

		{x = 2.5, y = 2.25, type = "prop_bookshelf"},
		{x = 3.5, y = 2.25, type = "prop_bookshelf"},
		{x = 7.5, y = 2.25, type = "prop_bookshelf"},
		{x = 8.5, y = 2.25, type = "prop_bookshelf"},

		{x = 5.5, y = 3.5, type = "prop_table_2"},
		{x = 5.5, y = 4.5, type = "health_powerup", chance = 0.2},
	]

[room.columns_room]
	tiles = [
		["VOID", "VOID", "VOID", "VOID", "WALL_DECORATION_1", "VOID", "VOID", "VOID", "WALL_DECORATION_1", "VOID", "VOID", "VOID", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "VOID", "VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID", "VOID", "FLOOR", "VOID"],
		["VOID", "FLOOR", "VOID", "VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID", "VOID", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "VOID", "VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID", "VOID", "FLOOR", "VOID"],
		["VOID", "FLOOR", "VOID", "VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID", "VOID", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID"]
	]
	connections = [
		{x = 0, y = 5, type = "LEFT"},
		{x = 12, y = 5, type = "RIGHT"},
		{x = 6, y = 10, type = "UP"},
		{x = 6, y = 0, type = "DOWN"}
	]
	spawns = [
		{x = 3, y = 1.5},
		{x = 3, y = 5.5},
		{x = 3, y = 9.5},
		{x = 6.5, y = 1.5},
		{x = 6.5, y = 9.5},
		{x = 10, y = 1.5},
		{x = 10, y = 5.5},
		{x = 10, y = 9.5}
	]
	placeholders = [
		# Torches
		{x = 5.5, y = 10, type = "torch"},
		{x = 7.5, y = 10, type = "torch"},
		{x = 1, y = 6, type = "torch"},
		{x = 1, y = 4, type = "torch"},
		{x = 12, y = 6, type = "torch"},
		{x = 12, y = 4, type = "torch"},

		{x = 3, y = 7, type = "torch"},
		{x = 10, y = 7, type = "torch"},
		{x = 3, y = 2, type = "torch"},
		{x = 10, y = 2, type = "torch"},
		{x = 6.5, y = 5.5, type = "health_powerup", chance = 0.2},
	]

[room.torture_room]
	tiles = [
		["VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID"]
	]
	connections = [
		{x = 0, y = 3, type = "LEFT"},
		{x = 6, y = 3, type = "RIGHT"},
		{x = 3, y = 6, type = "UP"},
		{x = 3, y = 0, type = "DOWN"}
	]
	spawns = [
		{x = 2, y = 2},
		{x = 2, y = 3.5},
		{x = 3.5, y = 2},
		{x = 3.5, y = 5},
		{x = 5, y = 2},
		{x = 5, y = 3.5},
		{x = 5, y = 5}
	]
	placeholders = [
		# Torches
		{x = 2.5, y = 6, type = "torch"},
		{x = 4.5, y = 6, type = "torch"},
		{x = 1, y = 4, type = "torch"},
		{x = 1, y = 2, type = "torch"},
		{x = 6, y = 4, type = "torch"},
		{x = 6, y = 2, type = "torch"},
		# Furniture
		{x = 5.5, y = 5.5, type = "prop_cage"},
		{x = 2, y = 5.5, type = "prop_cage"},
		{x = 1.5, y = 5, type = "prop_cage"},
		{x = 3.5, y = 3.5, type = "health_powerup", chance = 0.2},
	]

[room.cross_room]
	tiles = [
		["VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID"],
		["VOID", "VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID", "VOID"],
		["VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID"]
	]
	connections = [
		{x = 0, y = 4, type = "LEFT"},
		{x = 8, y = 4, type = "RIGHT"},
		{x = 4, y = 8, type = "UP"},
		{x = 4, y = 0, type = "DOWN"}
	]
	spawns = [
		{x = 2, y = 4.5},
		{x = 4.5, y = 2},
		{x = 4.5, y = 7},
		{x = 7, y = 4.5},
	]
	placeholders = [
		# Torches
		{x = 3.5, y = 8, type = "torch"},
		{x = 5.5, y = 8, type = "torch"},
		{x = 1, y = 5, type = "torch"},
		{x = 1, y = 3, type = "torch"},
		{x = 8, y = 5, type = "torch"},
		{x = 8, y = 3, type = "torch"},
		{x = 4.5, y = 4.5, type = "health_powerup", chance = 0.2},
	]

[room.horizontal_hallway]
	tiles = [
		["VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID"]
	]
	connections = [
		{x = 0, y = 2, type = "LEFT"},
		{x = 12, y = 2, type = "RIGHT"},
		{x = 3, y = 4, type = "UP"},
		{x = 3, y = 0, type = "DOWN"},
		{x = 9, y = 4, type = "UP"},
		{x = 9, y = 0, type = "DOWN"}
	]
	spawns = [
		{x = 2, y = 2.5},
		{x = 4, y = 2.5},
		{x = 6, y = 2.5},
		{x = 8, y = 2.5},
		{x = 10, y = 2.5},
	]
	placeholders = [
		# Torches
		{x = 2.5, y = 4, type = "torch"},
		{x = 4.5, y = 4, type = "torch"},
		{x = 8.5, y = 4, type = "torch"},
		{x = 10.5, y = 4, type = "torch"},
		{x = 1, y = 3, type = "torch"},
		{x = 1, y = 1, type = "torch"},
		{x = 12, y = 3, type = "torch"},
		{x = 12, y = 1, type = "torch"},
		# Furnitures
		{x = 2, y = 4.4, type = "prop_painting_1"},
		{x = 6.5, y = 4.4, type = "prop_painting_2"},
		{x = 11, y = 4.4, type = "prop_painting_3"},
	]

[room.vertical_hallway]
	tiles = [
		["VOID", "VOID", "WALL_DECORATION_3", "VOID", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "VOID", "VOID", "VOID", "VOID"],
	]
	connections = [
		{x = 2, y = 0, type = "DOWN"},
		{x = 2, y = 12, type = "UP"},
		{x = 0, y = 3, type = "LEFT"},
		{x = 4, y = 3, type = "RIGHT"},
		{x = 0, y = 9, type = "LEFT"},
		{x = 4, y = 9, type = "RIGHT"}
	]
	spawns = [
		{x = 2.5, y = 2},
		{x = 2.5, y = 4},
		{x = 2.5, y = 6},
		{x = 2.5, y = 8},
		{x = 2.5, y = 10},
	]
	placeholders = [
		# Torches
		{x = 1, y = 2, type = "torch"},
		{x = 1, y = 4, type = "torch"},
		{x = 1, y = 8, type = "torch"},
		{x = 1, y = 10, type = "torch"},
		{x = 4, y = 2, type = "torch"},
		{x = 4, y = 4, type = "torch"},
		{x = 4, y = 8, type = "torch"},
		{x = 4, y = 10, type = "torch"},
		{x = 3.5, y = 12, type = "torch"},
		{x = 1.5, y = 12, type = "torch"},
	]

[room.chest_room]
	tiles = [
		["VOID", "VOID", "VOID", "VOID", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "VOID", "VOID", "VOID", "VOID"]
	]
	connections = [
		{x = 0, y = 2, type = "LEFT"},
		{x = 4, y = 2, type = "RIGHT"},
		{x = 2, y = 4, type = "UP"},
		{x = 2, y = 0, type = "DOWN"}
	]
	spawns = [
		{x = 1.5, y = 2.5},
		{x = 2.5, y = 1.5},
		{x = 2.5, y = 3.5},
		{x = 3.5, y = 2.5},
	]
	placeholders = [
		# Torches
		{x = 1.5, y = 4, type = "torch"},
		{x = 3.5, y = 4, type = "torch"},
		{x = 1, y = 3, type = "torch"},
		{x = 1, y = 1, type = "torch"},
		{x = 4, y = 3, type = "torch"},
		{x = 4, y = 1, type = "torch"},
		{x = 2.5, y = 2, type = "chest"},
	]
