#
# Witch
#
[[animation]]
  texture = "characters_32b.png"
  name = "witch_walk"
  tilesize = 32
  frameDuration = 0.05
  loop = [0, 1, 2, 3, 4, 5, 6, 7]

[[animation]]
  texture = "characters_32b.png"
  name = "witch_attack"
  tilesize = 32
  frameDuration = 0.05
  sequence = [9, 10, 11, 12, 13, 14, 15, 16]

[[animation]]
  texture = "characters_32b.png"
  name = "witch_idle"
  tilesize = 32
  frameDuration = 0.5
  loop = [20, 21]

#
# Thief
#
[[animation]]
  texture = "characters_32b.png"
  name = "thief_walk"
  tilesize = 32
  frameDuration = 0.05
  loop = [46, 47, 48, 49, 50, 51, 52, 53]

[[animation]]
  texture = "characters_32b.png"
  name = "thief_attack"
  tilesize = 32
  frameDuration = 0.05
  sequence = [55, 56, 57, 58, 59, 60, 61, 62]

[[animation]]
  texture = "characters_32b.png"
  name = "thief_idle"
  tilesize = 32
  frameDuration = 0.5
  loop = [66, 67]

#
# Assasin
#
[[animation]]
  texture = "characters_32b.png"
  name = "assassin_walk"
  tilesize = 32
  frameDuration = 0.05
  loop = [23, 24, 25, 26, 27, 28]

[[animation]]
  texture = "characters_32b.png"
  name = "assassin_attack"
  tilesize = 32
  frameDuration = 0.05
  sequence = [32, 33, 34, 35, 36, 37, 38, 39, 40, 41]

[[animation]]
  texture = "characters_32b.png"
  name = "assassin_idle"
  tilesize = 32
  frameDuration = 0.5
  loop = [43, 44, 45]

#
# Creatures
#

# Acid slime
[[animation]]
  texture = "acid_slime.png"
  name = "slime_acid_idle"
  tilesize = 32
  frameDuration = 0.1
  loop = [0, 1, 2, 3, 4, 5, 6, 7, 8]

[[animation]]
  texture = "acid_slime.png"
  name = "slime_acid_attack"
  tilesize = 32
  frameDuration = 0.1
  loop = [9, 10, 11, 12, 13, 14, 15, 16, 17]

[[animation]]
  texture = "acid_slime.png"
  name = "slime_acid_die"
  tilesize = 32
  frameDuration = 0.07
  sequence = [18, 19, 20, 21, 22, 23, 24, 25, 26]

# Fire slime
[[animation]]
  texture = "fire_slime.png"
  name = "slime_fire_idle"
  tilesize = 32
  frameDuration = 0.1
  loop = [0, 1, 2, 3, 4, 5, 6]

[[animation]]
  texture = "fire_slime_explosion.png"
  name = "slime_fire_projectile"
  tilesize = 16
  frameDuration = 0.1
  loop = [0, 1]

[[animation]]
  texture = "fire_slime_explosion.png"
  name = "slime_fire_explosion"
  tilesize = 16
  frameDuration = 0.25
  sequence = [2, 3]

# Slime
[[animation]]
  texture = "slime.png"
  name = "slime_idle"
  tilesize = 32
  frameDuration = 0.25
  loop = [0, 1, 2, 1]

[[animation]]
  texture = "slime.png"
  name = "slime_blink"
  tilesize = 32
  frameDuration = 0.1
  loop = [2, 3, 4, 4, 4, 3, 2, 2, 2]

[[animation]]
  texture = "slime.png"
  name = "slime_die"
  tilesize = 32
  frameDuration = 0.07
  sequence = [5, 6, 7, 8, 9, 10, 11, 12]

# Slime spawn
[[animation]]
  texture = "slime_mini.png"
  name = "slime_mini_idle"
  tilesize = 16
  frameDuration = 0.25
  loop = [0, 1, 2, 1]

[[animation]]
  texture = "slime_mini.png"
  name = "slime_mini_blink"
  tilesize = 16
  frameDuration = 0.1
  loop = [2, 3, 4, 4, 4, 3, 2, 2, 2]

[[animation]]
  texture = "slime_mini.png"
  name = "slime_mini_die"
  tilesize = 16
  frameDuration = 0.07
  sequence = [5, 6, 7, 8, 9, 10, 11, 12]

# Slime blobs
[[animation]]
  texture = "slime_pool.png"
  name = "slime_pool_flood"
  tilesize = 32
  frameDuration = 0.1
  sequence = [0, 1, 2, 3, 4]

[[animation]]
  texture = "slime_pool.png"
  name = "slime_pool_dry"
  tilesize = 32
  frameDuration = 0.1
  sequence = [4, 3, 2, 1, 0]

[[animation]]
  texture = "slime_blobs.png"
  name = "slime_blob"
  tilesize = 16
  frameDuration = 0.1
  loop = [0, 1, 2, 3]

[[animation]]
  texture = "slime_blobs.png"
  name = "slime_splat"
  tilesize = 16
  frameDuration = 0.1
  sequence = [4, 5, 6, 7, 8, 9]

# Ghost
[[animation]]
  texture = "ghost_animation.png"
  name = "ghost_hover"
  tilesize = 32
  frameDuration = 0.1
  loop = [0, 1, 2, 3, 4, 5, 6, 7, 8]

# Cloud
[[animation]]
  texture = "cloud.png"
  name = "cloud"
  tilesize = 64
  frameDuration = 1.0
  sequence = [0]

# Exit Platform
[[animation]]
  texture = "exit_altar.png"
  name = "exit_platform_idle"
  tilesize = 64
  frameDuration = 1.0
  sequence = [0]

#
# Particles
#

# Wood chips
[[animation]]
  texture = "particles.png"
  name = "wood_particle_1"
  tilesize = 8
  frameDuration = 1.0
  sequence = [0]
[[animation]]
  texture = "particles.png"
  name = "wood_particle_2"
  tilesize = 8
  frameDuration = 1.0
  sequence = [1]
[[animation]]
  texture = "particles.png"
  name = "wood_particle_3"
  tilesize = 8
  frameDuration = 1.0
  sequence = [2]
[[animation]]
  texture = "particles.png"
  name = "wood_particle_4"
  tilesize = 8
  frameDuration = 1.0
  sequence = [3]
[[animation]]
  texture = "particles.png"
  name = "wood_particle_5"
  tilesize = 8
  frameDuration = 1.0
  sequence = [4]
[[animation]]
  texture = "particles.png"
  name = "wood_particle_6"
  tilesize = 8
  frameDuration = 1.0
  sequence = [5]
[[animation]]
  texture = "particles.png"
  name = "wood_particle_7"
  tilesize = 8
  frameDuration = 1.0
  sequence = [6]
[[animation]]
  texture = "particles.png"
  name = "wood_particle_8"
  tilesize = 8
  frameDuration = 1.0
  sequence = [7]

# Stone chips
[[animation]]
  texture = "particles.png"
  name = "stone_particle_1"
  tilesize = 8
  frameDuration = 1.0
  sequence = [8]
[[animation]]
  texture = "particles.png"
  name = "stone_particle_2"
  tilesize = 8
  frameDuration = 1.0
  sequence = [9]
[[animation]]
  texture = "particles.png"
  name = "stone_particle_3"
  tilesize = 8
  frameDuration = 1.0
  sequence = [10]
[[animation]]
  texture = "particles.png"
  name = "stone_particle_4"
  tilesize = 8
  frameDuration = 1.0
  sequence = [11]
[[animation]]
  texture = "particles.png"
  name = "stone_particle_5"
  tilesize = 8
  frameDuration = 1.0
  sequence = [12]
[[animation]]
  texture = "particles.png"
  name = "stone_particle_6"
  tilesize = 8
  frameDuration = 1.0
  sequence = [13]
[[animation]]
  texture = "particles.png"
  name = "stone_particle_7"
  tilesize = 8
  frameDuration = 1.0
  sequence = [14]
[[animation]]
  texture = "particles.png"
  name = "stone_particle_8"
  tilesize = 8
  frameDuration = 1.0
  sequence = [15]

# Droplets
[[animation]]
  texture = "particles.png"
  name = "droplet_start"
  tilesize = 8
  frameDuration = 0.05
  sequence = [16, 17, 18, 19]
[[animation]]
  texture = "particles.png"
  name = "droplet_fall"
  tilesize = 8
  frameDuration = 0.05
  sequence = [20]
[[animation]]
  texture = "particles.png"
  name = "droplet_end"
  tilesize = 8
  frameDuration = 0.05
  sequence = [21, 22, 23]

# Fireball
[[animation]]
  texture = "particles.png"
  name = "fireball"
  tilesize = 8
  frameDuration = 0.05
  loop = [24, 25, 26, 27, 28, 29, 30, 31]

# Flame
[[animation]]
  texture = "particles.png"
  name = "flame"
  tilesize = 8
  frameDuration = 0.05
  loop = [32, 33, 34, 35, 36, 37, 38, 39]

# Candle
[[animation]]
  texture = "particles.png"
  name = "candle"
  tilesize = 8
  frameDuration = 0.05
  loop = [40, 41, 42, 43, 44, 45, 46, 47]

# Health powerup
[[animation]]
  texture = "powerups.png"
  name = "powerup_health"
  tilesize = 20
  frameDuration = 1
  loop = [0]

# Tombstone
[[animation]]
  texture = "tombstone.png"
  name = "tombstone_spawn"
  tilesize = 32
  frameDuration = 0.05
  sequence = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

# Torch
[[animation]]
  texture = "torch.png"
  name = "torch_idle"
  tilesize = 32
  frameDuration = 0.05
  loop = [0, 1, 2, 3, 4, 5, 6, 7]

# Cat projectile
[[animation]]
  texture = "cat_projectile.png"
  name = "projectile_cat_right"
  tilesize = 24
  frameDuration = 0.25
  loop = [0, 1, 2, 3]
[[animation]]
  texture = "cat_projectile.png"
  name = "projectile_cat_up"
  tilesize = 24
  frameDuration = 0.25
  loop = [4, 5, 6, 7]
[[animation]]
  texture = "cat_projectile.png"
  name = "projectile_cat_down"
  tilesize = 24
  frameDuration = 0.25
  loop = [8, 9, 10, 11]

# Projectiles
[[animation]]
  texture = "projectile.png"
  name = "projectile_assassin_fly"
  tilesize = 16
  frameDuration = 0.1
  loop = [0]
[[animation]]
  texture = "projectile.png"
  name = "projectile_assassin_explode"
  tilesize = 16
  frameDuration = 0.1
  loop = [1, 2, 3, 4, 5]
[[animation]]
  texture = "projectile.png"
  name = "projectile_thief_fly"
  tilesize = 16
  frameDuration = 0.1
  loop = [6]
[[animation]]
  texture = "projectile.png"
  name = "projectile_thief_explode"
  tilesize = 16
  frameDuration = 0.1
  loop = [7, 8, 9, 10, 11]
[[animation]]
  texture = "projectile.png"
  name = "projectile_witch_fly"
  tilesize = 16
  frameDuration = 0.1
  loop = [12]
[[animation]]
  texture = "projectile.png"
  name = "projectile_witch_explode"
  tilesize = 16
  frameDuration = 0.1
  loop = [13, 14, 15, 16, 17]
