#
# Witch
#
[witch_walk]
  texture = "characters_32b.png"
  tilesize = 32
  frameDuration = 0.05
  loop = [0, 1, 2, 3, 4, 5, 6, 7]
[witch_attack]
  texture = "characters_32b.png"
  tilesize = 32
  frameDuration = 0.05
  sequence = [9, 10, 11, 12, 13, 14, 15, 16]
[witch_idle]
  texture = "characters_32b.png"
  tilesize = 32
  frameDuration = 0.5
  loop = [20, 21]

#
# Thief
#
[thief_walk]
  texture = "characters_32b.png"
  tilesize = 32
  frameDuration = 0.05
  loop = [46, 47, 48, 49, 50, 51, 52, 53]
[thief_attack]
  texture = "characters_32b.png"
  tilesize = 32
  frameDuration = 0.05
  sequence = [55, 56, 57, 58, 59, 60, 61, 62]
[thief_idle]
  texture = "characters_32b.png"
  tilesize = 32
  frameDuration = 0.5
  loop = [66, 67]

#
# Assasin
#
[assassin_walk]
  texture = "characters_32b.png"
  tilesize = 32
  frameDuration = 0.05
  loop = [23, 24, 25, 26, 27, 28]
[assassin_attack]
  texture = "characters_32b.png"
  tilesize = 32
  frameDuration = 0.05
  sequence = [32, 33, 34, 35, 36, 37, 38, 39, 40, 41]
[assassin_idle]
  texture = "characters_32b.png"
  tilesize = 32
  frameDuration = 0.5
  loop = [43, 44, 45]

#
# Creatures
#

# Acid slime
[slime_acid_idle]
  texture = "acid_slime.png"
  tilesize = 32
  frameDuration = 0.1
  loop = [0, 1, 2, 3, 4, 5, 6, 7, 8]
[slime_acid_attack]
  texture = "acid_slime.png"
  tilesize = 32
  frameDuration = 0.1
  loop = [9, 10, 11, 12, 13, 14, 15, 16, 17]
[slime_acid_die]
  texture = "acid_slime.png"
  tilesize = 32
  frameDuration = 0.07
  sequence = [18, 19, 20, 21, 22, 23, 24, 25, 26]

# Fire slime
[slime_fire_idle]
  texture = "fire_slime.png"
  tilesize = 32
  frameDuration = 0.1
  loop = [0, 1, 2, 3, 4, 5, 6]
[slime_fire_projectile]
  texture = "fire_slime_explosion.png"
  tilesize = 16
  frameDuration = 0.1
  loop = [0, 1]
[slime_fire_explosion]
  texture = "fire_slime_explosion.png"
  tilesize = 16
  frameDuration = 0.25
  sequence = [2, 3]

# Slime
[slime_idle]
  texture = "slime.png"
  tilesize = 32
  frameDuration = 0.25
  loop = [0, 1, 2, 1]
[slime_blink]
  texture = "slime.png"
  tilesize = 32
  frameDuration = 0.1
  loop = [2, 3, 4, 4, 4, 3, 2, 2, 2]
[slime_die]
  texture = "slime.png"
  tilesize = 32
  frameDuration = 0.07
  sequence = [5, 6, 7, 8, 9, 10, 11, 12, 13]

# Slime spawn
[slime_mini_idle]
  texture = "slime_mini.png"
  tilesize = 16
  frameDuration = 0.25
  loop = [0, 1, 2, 1]
[slime_mini_blink]
  texture = "slime_mini.png"
  tilesize = 16
  frameDuration = 0.1
  loop = [2, 3, 4, 4, 4, 3, 2, 2, 2]
[slime_mini_die]
  texture = "slime_mini.png"
  tilesize = 16
  frameDuration = 0.07
  sequence = [5, 6, 7, 8, 9, 10, 11, 12, 13]

# Slime blobs
[slime_pool_flood]
  texture = "slime_pool.png"
  tilesize = 32
  frameDuration = 0.1
  sequence = [0, 1, 2, 3, 4]
[slime_pool_dry]
  texture = "slime_pool.png"
  tilesize = 32
  frameDuration = 0.1
  sequence = [4, 3, 2, 1, 0]
[slime_blob]
  texture = "slime_blobs.png"
  tilesize = 16
  frameDuration = 0.1
  loop = [0, 1, 2, 3]
[slime_splat]
  texture = "slime_blobs.png"
  tilesize = 16
  frameDuration = 0.1
  sequence = [4, 5, 6, 7, 8, 9]

# Ghost
[ghost_hover]
  texture = "ghost_animation.png"
  tilesize = 32
  frameDuration = 0.1
  loop = [0, 1, 2, 3, 4, 5, 6, 7, 8]

# Cloud
[cloud]
  texture = "cloud.png"
  tilesize = 64
  frameDuration = 1.0
  sequence = [0]

# Exit Platform
[exit_platform_idle]
  texture = "exit_altar.png"
  tilesize = 64
  frameDuration = 1.0
  sequence = [0]

#
# Particles
#

# Wood chips
[wood_particle_1]
  texture = "particles.png"
  tilesize = 8
  frameDuration = 1.0
  sequence = [0]
[wood_particle_2]
  texture = "particles.png"
  tilesize = 8
  frameDuration = 1.0
  sequence = [1]
[wood_particle_3]
  texture = "particles.png"
  tilesize = 8
  frameDuration = 1.0
  sequence = [2]
[wood_particle_4]
  texture = "particles.png"
  tilesize = 8
  frameDuration = 1.0
  sequence = [3]
[wood_particle_5]
  texture = "particles.png"
  tilesize = 8
  frameDuration = 1.0
  sequence = [4]
[wood_particle_6]
  texture = "particles.png"
  tilesize = 8
  frameDuration = 1.0
  sequence = [5]
[wood_particle_7]
  texture = "particles.png"
  tilesize = 8
  frameDuration = 1.0
  sequence = [6]
[wood_particle_8]
  texture = "particles.png"
  tilesize = 8
  frameDuration = 1.0
  sequence = [7]

# Stone chips
[stone_particle_1]
  texture = "particles.png"
  tilesize = 8
  frameDuration = 1.0
  sequence = [8]
[stone_particle_2]
  texture = "particles.png"
  tilesize = 8
  frameDuration = 1.0
  sequence = [9]
[stone_particle_3]
  texture = "particles.png"
  tilesize = 8
  frameDuration = 1.0
  sequence = [10]
[stone_particle_4]
  texture = "particles.png"
  tilesize = 8
  frameDuration = 1.0
  sequence = [11]
[stone_particle_5]
  texture = "particles.png"
  tilesize = 8
  frameDuration = 1.0
  sequence = [12]
[stone_particle_6]
  texture = "particles.png"
  tilesize = 8
  frameDuration = 1.0
  sequence = [13]
[stone_particle_7]
  texture = "particles.png"
  tilesize = 8
  frameDuration = 1.0
  sequence = [14]
[stone_particle_8]
  texture = "particles.png"
  tilesize = 8
  frameDuration = 1.0
  sequence = [15]
[leave_particle]
  texture = "particles.png"
  tilesize = 8
  frameDuration = 0.05
  loop = [48, 48, 48, 49, 50, 51, 52, 53, 54, 55, 56, 56, 56, 55, 54, 53, 52, 51, 50, 49]

# Droplets
[droplet_start]
  texture = "particles.png"
  tilesize = 8
  frameDuration = 0.05
  sequence = [16, 17, 18, 19]
[droplet_fall]
  texture = "particles.png"
  tilesize = 8
  frameDuration = 0.05
  sequence = [20]
[droplet_end]
  texture = "particles.png"
  tilesize = 8
  frameDuration = 0.05
  sequence = [21, 22, 23]

# Fireball
[fireball]
  texture = "particles.png"
  tilesize = 8
  frameDuration = 0.05
  loop = [24, 25, 26, 27, 28, 29, 30, 31]

# Flame
[flame]
  texture = "particles.png"
  tilesize = 8
  frameDuration = 0.05
  loop = [32, 33, 34, 35, 36, 37, 38, 39]

# Candle
[candle]
  texture = "particles.png"
  tilesize = 8
  frameDuration = 0.05
  loop = [40, 41, 42, 43, 44, 45, 46, 47]

# Health powerup
[powerup_health]
  texture = "powerups.png"
  tilesize = 20
  frameDuration = 1
  loop = [0]

# Tombstone
[tombstone_spawn]
  texture = "tombstone.png"
  tilesize = 32
  frameDuration = 0.05
  sequence = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

# Torch
[torch_idle]
  texture = "torch.png"
  tilesize = 32
  frameDuration = 0.05
  loop = [0, 1, 2, 3, 4, 5, 6, 7]

# Chest
[chest_closed]
  texture = "furniture.png"
  tilesize = 48
  frameDuration = 1
  loop = [14]
[chest_opening]
  texture = "furniture.png"
  tilesize = 48
  frameDuration = 0.1
  sequence = [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]

#
# Furniture
#

# Doors
[door_horizontal]
  texture = "door.png"
  tilesize = 96
  frameDuration = 1
  loop = [1]
[door_vertical]
  texture = "door.png"
  tilesize = 96
  frameDuration = 1
  loop = [0]
# Bookcase
[prop_bookshelf]
  texture = "furniture.png"
  tilesize = 48
  frameDuration = 1
  loop = [0]
# Tables
[prop_table_1]
  texture = "furniture.png"
  tilesize = 48
  frameDuration = 1
  loop = [1]
[prop_table_2]
  texture = "furniture.png"
  tilesize = 48
  frameDuration = 1
  loop = [2]
# Cage
[prop_cage]
  texture = "furniture.png"
  tilesize = 48
  frameDuration = 1
  loop = [3]
# Bushes
[prop_bush_green]
  texture = "furniture.png"
  tilesize = 48
  frameDuration = 1
  loop = [4]
[prop_bush_green_small]
  texture = "furniture.png"
  tilesize = 48
  frameDuration = 1
  loop = [5]
[prop_bush_gold]
  texture = "furniture.png"
  tilesize = 48
  frameDuration = 1
  loop = [6]
[prop_bush_gold_small]
  texture = "furniture.png"
  tilesize = 48
  frameDuration = 1
  loop = [7]
[prop_bush_red]
  texture = "furniture.png"
  tilesize = 48
  frameDuration = 1
  loop = [8]
[prop_bush_red_small]
  texture = "furniture.png"
  tilesize = 48
  frameDuration = 1
  loop = [9]
[prop_bush_cyan]
  texture = "furniture.png"
  tilesize = 48
  frameDuration = 1
  loop = [10]
[prop_bush_cyan_small]
  texture = "furniture.png"
  tilesize = 48
  frameDuration = 1
  loop = [11]
[prop_bush_purple]
  texture = "furniture.png"
  tilesize = 48
  frameDuration = 1
  loop = [12]
[prop_bush_purple_small]
  texture = "furniture.png"
  tilesize = 48
  frameDuration = 1
  loop = [13]
[prop_painting_1]
  texture = "furniture.png"
  tilesize = 48
  frameDuration = 1
  loop = [28]
[prop_painting_2]
  texture = "furniture.png"
  tilesize = 48
  frameDuration = 1
  loop = [29]
[prop_painting_3]
  texture = "furniture.png"
  tilesize = 48
  frameDuration = 1
  loop = [30]

[coin]
  texture = "coin.png"
  tilesize = 8
  frameDuration = 0.12
  loop = [0, 1, 2, 3]

#
# Vegetation
#

[prop_grass_1]
  texture = "grass.png"
  tilesize = 24
  frameDuration = 0.5
  loop = [0, 1, 2, 1]
[prop_grass_2]
  texture = "grass.png"
  tilesize = 24
  frameDuration = 0.8
  loop = [3, 4]
[prop_grass_3]
  texture = "grass.png"
  tilesize = 24
  frameDuration = 0.8
  loop = [5, 6, 7, 6]
[prop_flower_1]
  texture = "grass.png"
  tilesize = 24
  frameDuration = 0.5
  loop = [8, 8, 9, 10, 10, 9]


# Cat projectile
[projectile_cat_right]
  texture = "cat_projectile.png"
  tilesize = 24
  frameDuration = 0.25
  loop = [0, 1, 2, 3]
[projectile_cat_up]
  texture = "cat_projectile.png"
  tilesize = 24
  frameDuration = 0.25
  loop = [4, 5, 6, 7]
[projectile_cat_down]
  texture = "cat_projectile.png"
  tilesize = 24
  frameDuration = 0.25
  loop = [8, 9, 10, 11]

# Projectiles
[projectile_assassin_fly]
  texture = "projectile.png"
  tilesize = 16
  frameDuration = 0.1
  loop = [0]
[projectile_assassin_explode]
  texture = "projectile.png"
  tilesize = 16
  frameDuration = 0.1
  loop = [1, 2, 3, 4, 5]
[projectile_thief_fly]
  texture = "projectile.png"
  tilesize = 16
  frameDuration = 0.1
  loop = [6]
[projectile_thief_explode]
  texture = "projectile.png"
  tilesize = 16
  frameDuration = 0.1
  loop = [7, 8, 9, 10, 11]
[projectile_witch_fly]
  texture = "projectile.png"
  tilesize = 16
  frameDuration = 0.1
  loop = [12]
[projectile_witch_explode]
  texture = "projectile.png"
  tilesize = 16
  frameDuration = 0.1
  loop = [13, 14, 15, 16, 17]

# Weapons
[weapon_sword]
  texture = "weapons.png"
  tilesize = 20
  frameDuration = 1
  sequence = [0]
[weapon_cat_staff]
  texture = "weapons.png"
  tilesize = 20
  frameDuration = 1
  sequence = [1]
[weapon_green_staff]
  texture = "weapons.png"
  tilesize = 20
  frameDuration = 1
  sequence = [2]

# Melee slash
[melee_slash]
  texture = "slash.png"
  tilesize = 32
  frameDuration = 0.025
  sequence = [0, 1, 2, 3, 4, 5, 6]
[invisible]
  texture = "void.png"
  tilesize = 1
  frameDuration = 1
  sequence = [0]

# Heart containers
[heart_container]
  texture = "heart_containers.png"
  tilesize = 12
  frameDuration = 0.25
  sequence = [0, 1, 2, 3, 4]

# Pixel
[pixel]
    texture = "fill.png"
    tilesize = 1
    frameDuration = 1
    loop = [0]