[application] # Accepts all LwjglApplicationConfiguration properties here...
    # Set the screen size
    width = 1600 # 1920
    height = 800 # 1080
    fullscreen = false
    title = "Dungeon crawler :)"
    # Uncomment these if you want to unlock FPS...
    # foregroundFPS = 0
    # backgroundFPS = 0
    # vSyncEnabled = false
[viewport]
    # Scaling gives the blocky appeal
    scale = 3.0
    gamma = 0.3
[map]
    items = ["weapon_sword", "weapon_cat_staff", "weapon_green_staff"]
    itemchance = 1.0
[rendering]
    noiseWidth = 128
    noiseHeight = 128
    noiseGrit = 0.2
    blurOpacity = 0.2
    blurDuration = 4.0

# Creatures
[[creatures]]
    id = "GHOST"
    maxTargetDistance = 300 # Targeting distance
    visibleTime = 2.0       # Visible time, in seconds
    visibleSpeed = 20       # Speed while visible
    stealthSpeed = 50       # Speed while stealth
    damagePerSecond = 2     # Damage dealth per second upon contact
[[creatures]]
    id = "SLIME"
    maxTargetDistance = 300 # Targeting distance
    jumpDistance = 50       # Jump distance
    damagePerSecond = 1     # Damage dealth per second upon contact
    attackFrequency = 3.0   # Frequency of attacks, in seconds
[[creatures]]
    id = "SLIME_ACID"
    maxTargetDistance = 300 # Targeting distance
    dashDistance = 150      # Dashing distance
    poolSeparation = 15     # Separation between acid pools
    poolDamage = 10         # Damage per second caused by the acid pool
    attackFrequency = 3.0   # Frequency of attacks, in seconds
    damagePerSecond = 5     # Damage dealth per second upon contact
[[creatures]]
    id = "SLIME_FIRE"
    maxTargetDistance = 300 # Targeting distance
    attackFrequency = 1.5   # Frequency of attacks, in seconds
    attackSpeed = 50        # Movement speed while attacking
    idleSpeed = 5           # Movement speed while idle
    damagePerSecond = 1     # Damage dealth per second upon contact
