[application] # Accepts all LwjglApplicationConfiguration properties here...
    # Set the screen size
    width = 1600 # 1920
    height = 800 # 1080
    fullscreen = false
    # Uncomment these if you want to unlock FPS...
    # foregroundFPS = 0
    # backgroundFPS = 0
    # vSyncEnabled = false
[viewport]
    # Position within screen where viewport gets drawn
    # posx = 400
    # posy = 200
    # Dimensions default to screen size if not set
    # width = 800
    # height = 400
    # Scaling gives the blocky appeal
    scale = 4.0
    gamma = 0.3
[map]
    # Base dimensions
    width = 40
    height = 40
    growth = 10
    #creatures = ["SLIME_FIRE"]
    creatures = ["GHOST", "SLIME", "SLIME_ACID", "SLIME_FIRE"]
    items = ["WEAPON_SWORD", "WEAPON_CAT_STAFF", "WEAPON_GREEN_STAFF"]
    itemchance = 1.0
[rendering]
    noiseHidth = 128
    noiseHeight = 128
    noiseGrit = 0.2
    blurOpacity = 0.2
    blurDuration = 4.0

# Characters
[[creatures]]
    id = "ASSASSIN"
    health = 100
    speed = 60
    friction = 10
[[creatures]]
    id = "THIEF"
    health = 100
    speed = 96
    friction = 10
[[creatures]]
    id = "WITCH"
    health = 100
    speed = 60
    friction = 10

# Creatures
[[creatures]]
    id = "GHOST"
    maxTargetDistance = 300 # Targeting distance
    visibleTime = 2.0       # Visible time, in seconds
    visibleSpeed = 20       # Speed while visible
    stealthSpeed = 40       # Speed while stealth
    damagePerSecond = 2     # Damage dealth per second upon contact
[[creatures]]
    id = "SLIME"
    maxTargetDistance = 300 # Targeting distance
    jumpDistance = 50       # Jump distance
    damagePerSecond = 1     # Damage dealth per second upon contact
    blobsOnDeath = 16       # Max amount of blobs spawned upon death
    attackFrequency = 3.0   # Frequency of attacks, in seconds
[[creatures]]
    id = "SLIME_ACID"
    maxTargetDistance = 300 # Targeting distance
    dashDistance = 150      # Dashing distance
    poolSeparation = 15     # Separation between acid pools
    poolDamage = 5          # Damage per second caused by the acid pool
    attackFrequency = 3.0   # Frequency of attacks, in seconds
    damagePerSecond = 1     # Damage dealth per second upon contact
[[creatures]]
    id = "SLIME_FIRE"
    maxTargetDistance = 300 # Targeting distance
    attackFrequency = 1.5   # Frequency of attacks, in seconds
    attackSpeed = 10        # Movement speed while attacking
    idleSpeed = 5           # Movement speed while idle
    damagePerSecond = 1     # Damage dealth per second upon contact

#
# Configuration for controllers
#
# povControl - POV control
# analogControlX - X analog axis (use negative value to invert axis)
# analogControlY - Y analog axis (use negative value to invert axis)
#
[[controllers]]
    id = "Logitech RumblePad 2 USB"
	povControl = 0
	analogControlX = 3
	analogControlY = -2
