[application] # Accepts all LwjglApplicationConfiguration properties here...
    # Set the screen size
    width = 1600
    height = 800
    # Uncomment these if you want to unlock FPS...
    # foregroundFPS = 0
    # backgroundFPS = 0
    # vSyncEnabled = false
[viewport]
    # Position within screen where viewport gets drawn
    # posx = 400
    # posy = 200
    # Dimensions default to screen size if not set
    # width = 800
    # height = 400
    # Scaling gives the blocky appeal
    scale = 3.0
[map]
    # Base dimensions
    width = 40
    height = 40
    growth = 10
    creatures = ["SLIME_FIRE"]#["GHOST", "SLIME", "SLIME_ACID", "SLIME_FIRE"]
    itemchance = 1.0
[noise]
    width = 128
    height = 128
    grit = 0.3 