[prop_bookshelf]
    animation = "prop_bookshelf"
    boundingBox = [48, 38]
    drawOffset = [24, 24]
    health = 500
[prop_table_1]
    animation = "prop_table_1"
    boundingBox = [42, 20]
    drawOffset = [24, 24]
    health = 500
[prop_table_2]
    animation = "prop_table_2"
    boundingBox = [42, 20]
    drawOffset = [24, 24]
    health = 500
[prop_cage]
    animation = "prop_cage"
    boundingBox = [20, 36]
    drawOffset = [24, 24]
    health = 1000
[prop_bush_green]
    animation = "prop_bush_green"
    boundingBox = [30, 30]
    drawOffset = [24, 23]
    health = 200
[prop_bush_gold]
    animation = "prop_bush_gold"
    boundingBox = [30, 30]
    drawOffset = [24, 23]
    health = 200
[prop_bush_red]
    animation = "prop_bush_red"
    boundingBox = [30, 30]
    drawOffset = [24, 23]
    health = 200
[prop_bush_cyan]
    animation = "prop_bush_cyan"
    boundingBox = [30, 30]
    drawOffset = [24, 23]
    health = 200
[prop_bush_purple]
    animation = "prop_bush_purple"
    boundingBox = [30, 30]
    drawOffset = [24, 23]
    health = 200
[prop_bush_green_small]
    animation = "prop_bush_green_small"
    boundingBox = [19, 20]
    drawOffset = [24, 24]
    health = 100
[prop_bush_gold_small]
    animation = "prop_bush_gold_small"
    boundingBox = [19, 20]
    drawOffset = [24, 24]
    health = 100
[prop_bush_red_small]
    animation = "prop_bush_red_small"
    boundingBox = [19, 20]
    drawOffset = [24, 24]
    health = 100
[prop_bush_cyan_small]
    animation = "prop_bush_cyan_small"
    boundingBox = [19, 20]
    drawOffset = [24, 24]
    health = 100
[prop_bush_purple_small]
    animation = "prop_bush_purple_small"
    boundingBox = [19, 20]
    drawOffset = [24, 24]
    health = 100
[prop_grass_1]
    animation = "prop_grass_1"
    boundingBox = [16, 18]
    drawOffset = [12, 10]
    health = 1
[prop_grass_2]
    animation = "prop_grass_2"
    boundingBox = [5, 4]
    drawOffset = [12, 3]
    health = 1
[prop_grass_3]
    animation = "prop_grass_3"
    boundingBox = [6, 6]
    drawOffset = [12, 4]
    health = 1
[prop_flower_1]
    animation = "prop_flower_1"
    boundingBox = [10, 16]
    drawOffset = [12, 15]
    health = 1



[door_horizontal]
    animation = "door_horizontal"
    boundingBox = [7, 96]
    drawOffset = [48, 32]
    health = 10
[door_horizontal_opening]
    animation = "door_horizontal"
    boundingBox = [7, 96]
    drawOffset = [48, 32]
    health = 10
    timeToLive = 1
    zSpeed = 40
    fadeOut = 1
[door_vertical]
    animation = "door_vertical"
    boundingBox = [48, 48]
    drawOffset = [48, 48]
    health = 10
[door_vertical_opening]
    animation = "door_vertical"
    boundingBox = [48, 48]
    drawOffset = [48, 48]
    health = 10
    timeToLive = 1
    zSpeed = 40
    fadeOut = 1

[particle_health_spec]
    animation = "pixel"
    boundingBox = [1, 1]
    drawOffset = [1, 1]
    color = "ff0000"
    hOscillate = [10, 5]
    timeToLive = 1
    fadeOut = 0.8
    zSpeed = 50
    zAccel = 100
[health_powerup_fade]
    animation = "powerup_health"
    boundingBox = [10, 10]
    drawOffset = [10, 10]
    timeToLive = 1.5
	light = ["192", "ff1932", "RAYS", "torchlight", "rotateFast"]
    fadeOut = 0.5
    fadeOutLight = true
    zAccel = 10
[health_powerup]
    animation = "powerup_health"
    boundingBox = [10, 10]
    drawOffset = [10, 10]
	light = ["192", "ff1932", "RAYS", "oscillate", "rotateFast"]
	zOscillate = [3, 8]


[smoke]
    animation = "cloud"
    boundingBox = [1, 1]
    drawOffset = [32, 32]
    timeToLive = 5
    color = "ffffff"
    fadeOut = 0.5
[exit_platform]
    animation = "exit_platform_idle"
    boundingBox = [20, 20]
    drawOffset = [32, 32]
    zIndex = -1
    light = ["300", "0000ff", "RAYS", "torchlight", "rotateSlow"]
[tombstone]
    animation = "tombstone_spawn"
    boundingBox = [10, 10]
    drawOffset = [16, 16]
[torch]
    animation = "torch_idle"
    boundingBox = [10, 10]
	drawOffset = [16, 16]
    light = ["80", "ffb232", "NORMAL", "torchlight"]
[chest]
    animation = "chest_closed"
    boundingBox = [22, 6]
	drawOffset = [24, 12]
    health = 50


[creature_slime_acid]
    animation = "slime_acid_idle"
    boundingBox = [22, 12]
    drawOffset = [16, 11]
    color = "ffffffb2"
    light = ["100", "a3d957ff", "RAYS", "rotateMedium"]
    speed = 100
    knockback = 1
    friction = 2
    health = 10
[creature_slime_acid_death]
    animation = "slime_acid_die"
    boundingBox = [22, 12]
    drawOffset = [16, 11]
    timeToLive = 1.7
    fadeOutLight = true
    light = ["150", "a3d957ff", "NORMAL"]
[creature_slime_acid_pool]
    animation = "slime_pool_flood"
    boundingBox = [22, 12]
    drawOffset = [16, 8]
    color = "a3d957ff"
    light = ["100", "a3d957ff", "NORMAL"]
    timeToLive = 5
    fadeOutLight = true
    zIndex = -1
[creature_slime_acid_blob]
    animation = "slime_blob"
    boundingBox = [6, 6]
    drawOffset = [8, 8]
    color = "a3d957ff"
    speed = 50
    timeToLive = 10
    zSpeed = 75 #(() -> Rand.between(50f, 100f))
    zAccel = -200
[creature_slime_acid_splat]
    animation = "slime_splat"
    boundingBox = [6, 6]
    drawOffset = [8, 8]
    color = "a3d957ff"
    timeToLive = 0.6

[creature_slime_fire]
    animation = "slime_fire_idle"
    boundingBox = [22, 12]
    drawOffset = [16, 11]
    color = "ffffffCC"
    light = ["100", "ff8800CC", "NORMAL", "torchlight"]
    speed = 20
    knockback = 1
    health = 5

[creature_ghost]
    animation = "ghost_hover"
    boundingBox = [16, 26]
    drawOffset = [16, 16]
    color = "ffffff88"
    knockback = 1
    light = ["200", "4a66ff88", "RAYS", "rotateSlow"]
    health = 10
    speed = 20
[creature_ghost_death]
    animation = "ghost_hover"
    boundingBox = [16, 26]
    drawOffset = [16, 16]
    color = "ff000088"
    light = ["200", "4a66ff88", "RAYS", "rotateSlow"]
    fadeOut = 0.5
    fadeOutLight = true
    timeToLive = 1
    zSpeed = 50

[creature_slime]
    boundingBox = [22, 12]
    drawOffset = [16, 11]
    # No color; gets assigned at random at the factory
    light = ["50", "ffffff88", "NORMAL"]
    speed = 100
    zSpeed = 0
    zAccel = -200
    knockback = 1
    friction = 1
    health = 7
[creature_slime_death]
    animation = "slime_die"
    boundingBox = [22, 12]
    drawOffset = [16, 11]
    color = "ffffff88"
    light = ["100", "ffffff88", "NORMAL"]
    fadeOutLight = true
    timeToLive = 1.6
[creature_slime_spawn]
    animation = "slime_mini_idle"
    boundingBox = [11, 6]
    drawOffset = [8, 6]
    light = ["25", "ffffff88", "NORMAL"]
    speed = 100
    zSpeed = 0
    zAccel = -200
    knockback = 1
    friction = 1
    health = 3
[creature_slime_spawn_death]
    animation = "slime_mini_die"
    boundingBox = [11, 6]
    drawOffset = [8, 6]
    color = "ffffff88"
    light = ["100", "ffffff88", "NORMAL"]
    fadeOutLight = true
    timeToLive = 1.6
[creature_slime_blob]
    animation = "slime_blob"
    boundingBox = [6, 6]
    drawOffset = [8, 8]
    speed = 50
    zSpeed = 75 #(() -> Rand.between(50f, 100f))
    zAccel = -200
    timeToLive = 10
[creature_slime_splat]
    animation = "slime_splat"
    boundingBox = [6, 6]
    drawOffset = [8, 8]
    timeToLive = 0.6

