[prop_bookshelf]
    animation = "prop_bookshelf"
    boundingBox = [48, 38]
    drawOffset = [24, 24]
    health = 500
[prop_table_1]
    animation = "prop_table_1"
    boundingBox = [42, 20]
    drawOffset = [24, 24]
    health = 500
[prop_table_2]
    animation = "prop_table_2"
    boundingBox = [42, 20]
    drawOffset = [24, 24]
    health = 500
[prop_cage]
    animation = "prop_cage"
    boundingBox = [20, 36]
    drawOffset = [24, 24]
    health = 1000
[prop_bush_green]
    animation = "prop_bush_green"
    boundingBox = [30, 30]
    drawOffset = [24, 23]
    health = 200
[prop_bush_gold]
    animation = "prop_bush_gold"
    boundingBox = [30, 30]
    drawOffset = [24, 23]
    health = 200
[prop_bush_red]
    animation = "prop_bush_red"
    boundingBox = [30, 30]
    drawOffset = [24, 23]
    health = 200
[prop_bush_cyan]
    animation = "prop_bush_cyan"
    boundingBox = [30, 30]
    drawOffset = [24, 23]
    health = 200
[prop_bush_purple]
    animation = "prop_bush_purple"
    boundingBox = [30, 30]
    drawOffset = [24, 23]
    health = 200
[prop_bush_green_small]
    animation = "prop_bush_green_small"
    boundingBox = [19, 20]
    drawOffset = [24, 24]
    health = 100
[prop_bush_gold_small]
    animation = "prop_bush_gold_small"
    boundingBox = [19, 20]
    drawOffset = [24, 24]
    health = 100
[prop_bush_red_small]
    animation = "prop_bush_red_small"
    boundingBox = [19, 20]
    drawOffset = [24, 24]
    health = 100
[prop_bush_cyan_small]
    animation = "prop_bush_cyan_small"
    boundingBox = [19, 20]
    drawOffset = [24, 24]
    health = 100
[prop_bush_purple_small]
    animation = "prop_bush_purple_small"
    boundingBox = [19, 20]
    drawOffset = [24, 24]
    health = 100
[prop_grass_1]
    animation = "prop_grass_1"
    boundingBox = [16, 18]
    drawOffset = [12, 10]
    health = 1
[prop_grass_2]
    animation = "prop_grass_2"
    boundingBox = [5, 4]
    drawOffset = [12, 3]
    health = 1
[prop_grass_3]
    animation = "prop_grass_3"
    boundingBox = [6, 6]
    drawOffset = [12, 4]
    health = 1
[prop_flower_1]
    animation = "prop_flower_1"
    boundingBox = [10, 16]
    drawOffset = [12, 15]
    health = 1



[door_horizontal]
    animation = "door_horizontal"
    boundingBox = [7, 96]
    drawOffset = [48, 32]
    health = 10
[door_horizontal_opening]
    animation = "door_horizontal"
    boundingBox = [7, 96]
    drawOffset = [48, 32]
    health = 10
    timeToLive = 1
    zSpeed = 40
    fadeOut = 1
[door_vertical]
    animation = "door_vertical"
    boundingBox = [48, 48]
    drawOffset = [48, 48]
    health = 10
[door_vertical_opening]
    animation = "door_vertical"
    boundingBox = [48, 48]
    drawOffset = [48, 48]
    health = 10
    timeToLive = 1
    zSpeed = 40
    fadeOut = 1

[particle_health_spec]
    animation = "pixel"
    boundingBox = [1, 1]
    drawOffset = [1, 1]
    color = "ff0000"
    hOscillate = [10, 5]
    timeToLive = 1
    fadeOut = 0.8
    zSpeed = 50
    zAccel = 100
[health_powerup_fade]
    animation = "powerup_health"
    boundingBox = [10, 10]
    drawOffset = [10, 10]
    timeToLive = 1.5
    #light = vanishLight
    fadeOut = 0.5
    fadeOutLight = true
    zAccel = 10
[health_powerup]
    animation = "powerup_health"
    boundingBox = [10, 10]
    drawOffset = [10, 10]
	#light = light
	zOscillate = [3, 8]


[smoke]
    animation = "cloud"
    boundingBox = [1, 1]
    drawOffset = [32, 32]
    timeToLive = 5
    color = "ffffff"
    fadeOut = 0.5
[exit_platform]
    animation = "exit_platform_idle"
    boundingBox = [20, 20]
    drawOffset = [32, 32]
    zIndex = -1
[tombstone]
    animation = "tombstone_spawn"
    boundingBox = [10, 10]
    drawOffset = [16, 16]
