[empty_room]
	tiles = [
		["VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID"]
	]
	connections = [
		{x = 0, y = 3, type = "LEFT"},
		{x = 6, y = 3, type = "RIGHT"},
		{x = 3, y = 6, type = "UP"},
		{x = 3, y = 0, type = "DOWN"}
	]
	spawns = [
		{x = 2, y = 2},
		{x = 2, y = 3.5},
		{x = 2, y = 5},
		{x = 3.5, y = 2},
		{x = 3.5, y = 5},
		{x = 5, y = 2},
		{x = 5, y = 3.5},
		{x = 5, y = 5}
	]
	placeholders = [
		# Torches
		{x = 2.5, y = 6.5, type = "TORCH"},
		{x = 4.5, y = 6.5, type = "TORCH"},
		{x = 1, y = 4.5, type = "TORCH"},
		{x = 1, y = 2.5, type = "TORCH"},
		{x = 6, y = 4.5, type = "TORCH"},
		{x = 6, y = 2.5, type = "TORCH"},
		{x = 3.5, y = 3.5, type = "HEALTH_POWERUP", chance = 0.2},
	]

[dinning_room]
	tiles = [
		["VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID"]
	]
	connections = [
		{x = 0, y = 3, type = "LEFT"},
		{x = 6, y = 3, type = "RIGHT"},
		{x = 3, y = 6, type = "UP"},
		{x = 3, y = 0, type = "DOWN"}
	]
	spawns = [
		{x = 2, y = 3.5},
		{x = 2, y = 5},
		{x = 3.5, y = 2},
		{x = 5, y = 2},
	]
	placeholders = [
		# Torches
		{x = 2.5, y = 6.5, type = "TORCH"},
		{x = 4.5, y = 6.5, type = "TORCH"},
		{x = 1, y = 4.5, type = "TORCH"},
		{x = 1, y = 2.5, type = "TORCH"},
		{x = 6, y = 4.5, type = "TORCH"},
		{x = 6, y = 2.5, type = "TORCH"},
		# Furniture
		{x = 5, y = 5, type = "TABLE"},
		{x = 4, y = 5, type = "TABLE"},
		{x = 5, y = 3.5, type = "TABLE2"},
		{x = 4, y = 3.5, type = "TABLE"}
		{x = 2, y = 2, type = "HEALTH_POWERUP", chance = 0.2},
	]

[library]
	tiles = [
		["VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID"]
	]
	connections = [
		{x = 0, y = 3, type = "LEFT"},
		{x = 10, y = 3, type = "RIGHT"},
		{x = 5, y = 6, type = "UP"},
		{x = 5, y = 0, type = "DOWN"}
	]
	spawns = [
		{x = 3, y = 1.5},
		{x = 3, y = 3.5},
		{x = 3, y = 5.5},
		{x = 5.5, y = 2},
		{x = 5.5, y = 4},
		{x = 8, y = 1.5},
		{x = 8, y = 3.5},
		{x = 8, y = 5.5}
	]
	placeholders = [
		# Torches
		{x = 4.5, y = 6.5, type = "TORCH"},
		{x = 6.5, y = 6.5, type = "TORCH"},
		{x = 1, y = 4.5, type = "TORCH"},
		{x = 1, y = 2.5, type = "TORCH"},
		{x = 10, y = 4.5, type = "TORCH"},
		{x = 10, y = 2.5, type = "TORCH"},

		{x = 4, y = 4.25, type = "TORCH"},
		{x = 7, y = 4.25, type = "TORCH"},
		{x = 4, y = 2.25, type = "TORCH"},
		{x = 7, y = 2.25, type = "TORCH"},
		# Furniture
		{x = 1.5, y = 6.25, type = "BOOKSHELF"},
		{x = 2.5, y = 6.25, type = "BOOKSHELF"},
		{x = 3.5, y = 6.25, type = "BOOKSHELF"},
		{x = 7.5, y = 6.25, type = "BOOKSHELF"},
		{x = 8.5, y = 6.25, type = "BOOKSHELF"},
		{x = 9.5, y = 6.25, type = "BOOKSHELF"},

		{x = 2.5, y = 4.25, type = "BOOKSHELF"},
		{x = 3.5, y = 4.25, type = "BOOKSHELF"},
		{x = 7.5, y = 4.25, type = "BOOKSHELF"},
		{x = 8.5, y = 4.25, type = "BOOKSHELF"},

		{x = 2.5, y = 2.25, type = "BOOKSHELF"},
		{x = 3.5, y = 2.25, type = "BOOKSHELF"},
		{x = 7.5, y = 2.25, type = "BOOKSHELF"},
		{x = 8.5, y = 2.25, type = "BOOKSHELF"},

		{x = 5.5, y = 3.5, type = "TABLE2"},
		{x = 5.5, y = 4.5, type = "HEALTH_POWERUP", chance = 0.2},
	]

[columns_room]
	tiles = [
		["VOID", "VOID", "VOID", "VOID", "WALL_DECORATION_1", "VOID", "VOID", "VOID", "WALL_DECORATION_1", "VOID", "VOID", "VOID", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "VOID", "VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID", "VOID", "FLOOR", "VOID"],
		["VOID", "FLOOR", "VOID", "VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID", "VOID", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "VOID", "VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID", "VOID", "FLOOR", "VOID"],
		["VOID", "FLOOR", "VOID", "VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID", "VOID", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID"]
	]
	connections = [
		{x = 0, y = 5, type = "LEFT"},
		{x = 12, y = 5, type = "RIGHT"},
		{x = 6, y = 10, type = "UP"},
		{x = 6, y = 0, type = "DOWN"}
	]
	spawns = [
		{x = 3, y = 1.5},
		{x = 3, y = 5.5},
		{x = 3, y = 9.5},
		{x = 6.5, y = 1.5},
		{x = 6.5, y = 9.5},
		{x = 10, y = 1.5},
		{x = 10, y = 5.5},
		{x = 10, y = 9.5}
	]
	placeholders = [
		# Torches
		{x = 5.5, y = 10.5, type = "TORCH"},
		{x = 7.5, y = 10.5, type = "TORCH"},
		{x = 1, y = 6.5, type = "TORCH"},
		{x = 1, y = 4.5, type = "TORCH"},
		{x = 12, y = 6.5, type = "TORCH"},
		{x = 12, y = 4.5, type = "TORCH"},

		{x = 3, y = 7.25, type = "TORCH"},
		{x = 10, y = 7.25, type = "TORCH"},
		{x = 3, y = 2.25, type = "TORCH"},
		{x = 10, y = 2.25, type = "TORCH"},
		{x = 6.5, y = 5.5, type = "HEALTH_POWERUP", chance = 0.2},
	]

[torture_room]
	tiles = [
		["VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID"]
	]
	connections = [
		{x = 0, y = 3, type = "LEFT"},
		{x = 6, y = 3, type = "RIGHT"},
		{x = 3, y = 6, type = "UP"},
		{x = 3, y = 0, type = "DOWN"}
	]
	spawns = [
		{x = 2, y = 2},
		{x = 2, y = 3.5},
		{x = 3.5, y = 2},
		{x = 3.5, y = 5},
		{x = 5, y = 2},
		{x = 5, y = 3.5},
		{x = 5, y = 5}
	]
	placeholders = [
		# Torches
		{x = 2.5, y = 6.5, type = "TORCH"},
		{x = 4.5, y = 6.5, type = "TORCH"},
		{x = 1, y = 4.5, type = "TORCH"},
		{x = 1, y = 2.5, type = "TORCH"},
		{x = 6, y = 4.5, type = "TORCH"},
		{x = 6, y = 2.5, type = "TORCH"},
		# Furniture
		{x = 5.5, y = 5.5, type = "CAGE"},
		{x = 2, y = 5.5, type = "CAGE"},
		{x = 1.5, y = 5, type = "CAGE"},
		{x = 3.5, y = 3.5, type = "HEALTH_POWERUP", chance = 0.2},
	]

[cross_room]
	tiles = [
		["VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID"],
		["VOID", "VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID", "VOID"],
		["VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID"]
	]
	connections = [
		{x = 0, y = 4, type = "LEFT"},
		{x = 8, y = 4, type = "RIGHT"},
		{x = 4, y = 8, type = "UP"},
		{x = 4, y = 0, type = "DOWN"}
	]
	spawns = [
		{x = 2, y = 4.5},
		{x = 4.5, y = 2},
		{x = 4.5, y = 7},
		{x = 7, y = 4.5},
	]
	placeholders = [
		# Torches
		{x = 3.5, y = 8.5, type = "TORCH"},
		{x = 5.5, y = 8.5, type = "TORCH"},
		{x = 1, y = 5.5, type = "TORCH"},
		{x = 1, y = 3.5, type = "TORCH"},
		{x = 8, y = 5.5, type = "TORCH"},
		{x = 8, y = 3.5, type = "TORCH"},
		{x = 4.5, y = 4.5, type = "HEALTH_POWERUP", chance = 0.2},
	]

[horizontal_hallway]
	tiles = [
		["VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID", "VOID"]
	]
	connections = [
		{x = 0, y = 2, type = "LEFT"},
		{x = 12, y = 2, type = "RIGHT"},
		{x = 3, y = 4, type = "UP"},
		{x = 3, y = 0, type = "DOWN"},
		{x = 9, y = 4, type = "UP"},
		{x = 9, y = 0, type = "DOWN"}
	]
	spawns = [
		{x = 2, y = 2.5},
		{x = 4, y = 2.5},
		{x = 6, y = 2.5},
		{x = 8, y = 2.5},
		{x = 10, y = 2.5},
	]
	placeholders = [
		# Torches
		{x = 2.5, y = 4.5, type = "TORCH"},
		{x = 4.5, y = 4.5, type = "TORCH"},
		{x = 8.5, y = 4.5, type = "TORCH"},
		{x = 10.5, y = 4.5, type = "TORCH"},
		{x = 1, y = 3.5, type = "TORCH"},
		{x = 1, y = 1.5, type = "TORCH"},
		{x = 12, y = 3.5, type = "TORCH"},
		{x = 12, y = 1.5, type = "TORCH"},
		# Furnitures
		{x = 2, y = 4.4, type = "PAINTING_1"},
		{x = 6.5, y = 4.4, type = "PAINTING_2"},
		{x = 11, y = 4.4, type = "PAINTING_3"},
	]
[vertical_hallway]
	tiles = [
		["VOID", "VOID", "VOID", "VOID", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "VOID", "VOID", "VOID", "VOID"],
	]
	connections = [
		{x = 2, y = 0, type = "DOWN"},
		{x = 2, y = 12, type = "UP"},
		{x = 0, y = 3, type = "LEFT"},
		{x = 4, y = 3, type = "RIGHT"},
		{x = 0, y = 9, type = "LEFT"},
		{x = 4, y = 9, type = "RIGHT"}
	]
	spawns = [
		{x = 2.5, y = 2},
		{x = 2.5, y = 4},
		{x = 2.5, y = 6},
		{x = 2.5, y = 8},
		{x = 2.5, y = 10},
	]
	placeholders = [
		# Torches
		{x = 1, y = 2.5, type = "TORCH"},
		{x = 1, y = 4.5, type = "TORCH"},
		{x = 1, y = 8.5, type = "TORCH"},
		{x = 1, y = 10.5, type = "TORCH"},
		{x = 4, y = 2.5, type = "TORCH"},
		{x = 4, y = 4.5, type = "TORCH"},
		{x = 4, y = 8.5, type = "TORCH"},
		{x = 4, y = 10.5, type = "TORCH"},
		{x = 3.5, y = 12.5, type = "TORCH"},
		{x = 1.5, y = 12.5, type = "TORCH"},
	]
[chest_room]
	tiles = [
		["VOID", "VOID", "VOID", "VOID", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "FLOOR", "FLOOR", "FLOOR", "VOID"],
		["VOID", "VOID", "VOID", "VOID", "VOID"]
	]
	connections = [
		{x = 0, y = 2, type = "LEFT"},
		{x = 4, y = 2, type = "RIGHT"},
		{x = 2, y = 4, type = "UP"},
		{x = 2, y = 0, type = "DOWN"}
	]
	spawns = [
		{x = 1.5, y = 2.5},
		{x = 2.5, y = 1.5},
		{x = 2.5, y = 3.5},
		{x = 3.5, y = 2.5},
	]
	placeholders = [
		# Torches
		{x = 1.5, y = 4.5, type = "TORCH"},
		{x = 3.5, y = 4.5, type = "TORCH"},
		{x = 1, y = 3.5, type = "TORCH"},
		{x = 1, y = 1.5, type = "TORCH"},
		{x = 4, y = 3.5, type = "TORCH"},
		{x = 4, y = 1.5, type = "TORCH"},
		{x = 2.5, y = 2.5, type = "CHEST"},
	]
