[animation.door_horizontal]
    texture = "door.png"
    tilesize = 96
    frameDuration = 1
    loop = [1]
[animation.door_vertical]
    texture = "door.png"
    tilesize = 96
    frameDuration = 1
    loop = [0]

[prototype.door_horizontal]
    animation = "door_horizontal"
    boundingBox = [7, 96]
    drawOffset = [48, 32]
    health = 10
    solid = true
[prototype.door_horizontal_opening]
    animation = "door_horizontal"
    boundingBox = [7, 96]
    drawOffset = [48, 32]
    health = 10
    timeToLive = 1
    zSpeed = 40
    fadeOut = 1
    solid = true
    canBeHurt = false
[prototype.door_vertical]
    animation = "door_vertical"
    boundingBox = [48, 48]
    drawOffset = [48, 48]
    health = 10
    solid = true
    castsShadow = true
[prototype.door_vertical_opening]
    animation = "door_vertical"
    boundingBox = [48, 48]
    drawOffset = [48, 48]
    health = 10
    timeToLive = 1
    zSpeed = 40
    fadeOut = 1
    solid = true
    canBeHurt = false
    castsShadow = true
