# Slime
[animation.slime_acid_idle]
    texture = "acid_slime.png"
    tilesize = 32
    frameDuration = 0.1
    loop = [0, 1, 2, 3, 4, 5, 6, 7, 8]
[animation.slime_acid_attack]
    texture = "acid_slime.png"
    tilesize = 32
    frameDuration = 0.1
    loop = [9, 10, 11, 12, 13, 14, 15, 16, 17]
[prototype.creature_slime_acid]
    animation = "slime_acid_idle"
    boundingBox = [22, 12]
    drawOffset = [16, 11]
    color = "ffffffb2"
    light = ["100", "a3d957ff", "RAYS", "rotateMedium"]
    speed = 100
    knockback = 1
    friction = 2
    health = 10
    castsShadow = true

# Death
[animation.slime_acid_die]
    texture = "acid_slime.png"
    tilesize = 32
    frameDuration = 0.07
    sequence = [18, 19, 20, 21, 22, 23, 24, 25, 26]
[prototype.creature_slime_acid_death]
    inherit = "creature_slime_acid"
    animation = "slime_acid_die"
    timeToLive = 1.7
    fadeOutLight = true
    light = ["150", "a3d957ff", "NORMAL"]

# Acid pool
[animation.slime_pool_flood]
	texture = "slime_pool.png"
	tilesize = 32
	frameDuration = 0.1
	sequence = [0, 1, 2, 3, 4]
[animation.slime_pool_dry]
	texture = "slime_pool.png"
	tilesize = 32
	frameDuration = 0.1
	sequence = [4, 3, 2, 1, 0]
[prototype.creature_slime_acid_pool]
    animation = "slime_pool_flood"
    boundingBox = [22, 12]
    drawOffset = [16, 16]
    color = "a3d957ff"
    light = ["100", "a3d957ff", "NORMAL"]
    timeToLive = 5
    fadeOutLight = true
    zIndex = -1

# Blob
[prototype.creature_slime_acid_blob]
    animation = "slime_blob"
    boundingBox = [6, 6]
    drawOffset = [8, 8]
    color = "a3d957ff"
    speed = 50
    timeToLive = 10
    zSpeed = 75 #(() -> Rand.between(50f, 100f))
    zAccel = -200
    castsShadow = true

# Blob explosion
[prototype.creature_slime_acid_splat]
    inherits = "creature_slime_acid_blob"
    animation = "slime_splat"
    timeToLive = 0.6
