[prototype.player_character]
    health = 100
    friction = 10
    speed = 60
    castShadow = true
    knockback = 0.5
#
# Witch
#
[animation.witch_walk]
    texture = "characters_32b.png"
    tilesize = 32
    frameDuration = 0.05
    loop = [0, 1, 2, 3, 4, 5, 6, 7]
[animation.witch_attack]
    texture = "characters_32b.png"
    tilesize = 32
    frameDuration = 0.05
    sequence = [9, 10, 11, 12, 13, 14, 15, 16]
[animation.witch_idle]
    texture = "characters_32b.png"
    tilesize = 32
    frameDuration = 0.5
    loop = [20, 21]

[prototype.player_witch]
    inherits = "player_character"
    animation = "witch_idle"
    boundingBox = [14, 12]
    drawOffset = [16, 6]

#
# Thief
#
[animation.thief_walk]
    texture = "characters_32b.png"
    tilesize = 32
    frameDuration = 0.05
    loop = [46, 47, 48, 49, 50, 51, 52, 53]
[animation.thief_attack]
    texture = "characters_32b.png"
    tilesize = 32
    frameDuration = 0.05
    sequence = [55, 56, 57, 58, 59, 60, 61, 62]
[animation.thief_idle]
    texture = "characters_32b.png"
    tilesize = 32
    frameDuration = 0.5
    loop = [66, 67]

[prototype.player_thief]
    inherits = "player_character"
    animation = "thief_idle"
    boundingBox = [14, 12]
    drawOffset = [16, 6]
    speed = 96

#
# Assasin
#
[animation.assassin_walk]
    texture = "characters_32b.png"
    tilesize = 32
    frameDuration = 0.05
    loop = [23, 24, 25, 26, 27, 28]
[animation.assassin_attack]
    texture = "characters_32b.png"
    tilesize = 32
    frameDuration = 0.05
    sequence = [32, 33, 34, 35, 36, 37, 38, 39, 40, 41]
[animation.assassin_idle]
    texture = "characters_32b.png"
    tilesize = 32
    frameDuration = 0.5
    loop = [43, 44, 45]

[prototype.player_assassin]
    inherits = "player_character"
    animation = "assassin_idle"
    boundingBox = [14, 12]
    drawOffset = [16, 6]

